force-app/main/default/objects/Income_Currency__c/Income_Currency__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Income Currency</label>
</CustomObject>

force-app/main/default/objects/Income_Currency__c/fields/Agency_Fee__c.field-meta.xml
<CustomField>
    <fullName>Agency_Fee__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Agency_Fee_Currency__c&apos;</defaultValue>
    <label>Agency Fee</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Agent_Discount__c.field-meta.xml
<CustomField>
    <fullName>Agent_Discount__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Agent Discount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Agent_Discount_From_Production__c.field-meta.xml
<CustomField>
    <fullName>Agent_Discount_From_Production__c</fullName>
    <label>Agent_Discount_From_Production</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Commission Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Commission_Amount_from_Production__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount_from_Production__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Commission Amount from Production</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Commission_From_Production_After_Tax__c.field-meta.xml
<CustomField>
    <fullName>Commission_From_Production_After_Tax__c</fullName>
    <label>Commission From Production After Tax</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Credit_Fees__c.field-meta.xml
<CustomField>
    <fullName>Credit_Fees__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Credit Fees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Credit_Fees_From_Production__c.field-meta.xml
<CustomField>
    <fullName>Credit_Fees_From_Production__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Credit Fees From Production</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Fees__c.field-meta.xml
<CustomField>
    <fullName>Fees__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Fees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Fees_From_Production__c.field-meta.xml
<CustomField>
    <fullName>Fees_From_Production__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Fees From Production</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Other_Commission__c.field-meta.xml
<CustomField>
    <fullName>Other_Commission__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Other Commission</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Premium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Premium_Bruto__c.field-meta.xml
<CustomField>
    <fullName>Premium_Bruto__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Premium Bruto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Premium_From_Production__c.field-meta.xml
<CustomField>
    <fullName>Premium_From_Production__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Premium From Production</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Premium_To_Pay__c.field-meta.xml
<CustomField>
    <fullName>Premium_To_Pay__c</fullName>
    <label>Premium To Pay</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/subagentfees__c.field-meta.xml
<CustomField>
    <fullName>subagentfees__c</fullName>
    <label>subagentfees</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Underwriter_Commission__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_Commission__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Premium_Currency__c&apos;</defaultValue>
    <label>Underwriter Commission</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Income_Currency__c/fields/Value_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Value_Date_Field__c</fullName>
    <defaultValue>&apos;HPC_Novidea__Bordero_Date__c&apos;</defaultValue>
    <label>Value Date Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/Policy_Currency__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Policy Currency</label>
</CustomObject>

force-app/main/default/objects/Policy_Currency__c/fields/Agency_Fee__c.field-meta.xml
<CustomField>
    <fullName>Agency_Fee__c</fullName>
    <label>Agency Fee</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>Commission Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/fields/Income_Amount__c.field-meta.xml
<CustomField>
    <fullName>Income_Amount__c</fullName>
    <label>Income Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/fields/Premium_Amount__c.field-meta.xml
<CustomField>
    <fullName>Premium_Amount__c</fullName>
    <label>Premium Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/fields/Premium_to_Pay__c.field-meta.xml
<CustomField>
    <fullName>Premium_to_Pay__c</fullName>
    <label>Premium to Pay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/fields/Unpaid_Agency_Fee__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Agency_Fee__c</fullName>
    <label>Unpaid Agency Fee</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/fields/Unpaid_Premium__c.field-meta.xml
<CustomField>
    <fullName>Unpaid_Premium__c</fullName>
    <label>Unpaid Premium</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Currency__c/fields/Value_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Value_Date_Field__c</fullName>
    <label>Value Date Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPolicyTriggerHowden.cls
@isTest(seeAllData=false)
private with sharing class TestPolicyTriggerHowden {
	@TestSetup
	private static void makeData() {
		Database.insert(
			new Policy_Currency__c(
				Agency_Fee__c = 'Novidea_HPC__Agency_Fees_Currency__c',
				Commission_Amount__c = 'Novidea_HPC__Premium_Amount_Currency__c',
				Income_Amount__c = 'Novidea_HPC__Premium_Amount_Currency__c',
				Premium_Amount__c = 'Novidea_HPC__Premium_Amount_Currency__c',
				Premium_to_Pay__c = 'Novidea_HPC__Premium_Amount_Currency__c',
				Unpaid_Agency_Fee__c = 'Novidea_HPC__Agency_Fees_Currency__c',
				Unpaid_Premium__c = 'Novidea_HPC__Premium_Amount_Currency__c',
				Value_Date_Field__c = 'Novidea_HPC__Value_Date__c'
			)
		);
		Database.insert(
			new Income_Currency__c(
				Agency_Fee__c = 'Novidea_HPC__Agency_Fee_Currency__c',
				Agent_Discount_From_Production__c = 'Novidea_HPC__Premium_Currency__c',
				Agent_Discount__c = 'Novidea_HPC__Premium_Currency__c',
				Commission_Amount__c = 'Novidea_HPC__Premium_Currency__c',
				Commission_Amount_from_Production__c = 'Novidea_HPC__Premium_Currency__c',
				Commission_From_Production_After_Tax__c = 'Novidea_HPC__Premium_Currency__c',
				Credit_Fees__c = 'Novidea_HPC__Premium_Currency__c',
				Credit_Fees_From_Production__c = 'Novidea_HPC__Premium_Currency__c',
				Fees__c = 'Novidea_HPC__Premium_Currency__c',
				Fees_From_Production__c = 'Novidea_HPC__Premium_Currency__c',
				Other_Commission__c = 'Novidea_HPC__Premium_Currency__c',
				Premium__c = 'Novidea_HPC__Premium_Currency__c',
				Premium_Bruto__c = 'Novidea_HPC__Premium_Currency__c',
				Premium_From_Production__c = 'Novidea_HPC__Premium_Currency__c',
				Premium_To_Pay__c = 'Novidea_HPC__Premium_Currency__c',
				subagentfees__c = 'Novidea_HPC__Premium_Currency__c',
				Underwriter_Commission__c = 'Novidea_HPC__Premium_Currency__c',
				Value_Date_Field__c = 'Value_Date__c'
			)
		);
	}
	@isTest
	private static void testInsert() {
		Database.insert(new Novidea_HPC__Policy__c());
	}
}