force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls Currency related settings</description>
    <label>Currency</label>
</CustomObject>

force-app/main/default/objects/Currency__c/fields/Currency_Manager__c.field-meta.xml
<CustomField>
    <fullName>Currency_Manager__c</fullName>
    <label>Currency Manager</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Current_Exchange_Rate_Source_URL__c.field-meta.xml
<CustomField>
    <fullName>Current_Exchange_Rate_Source_URL__c</fullName>
    <defaultValue>&quot;http://www.bankisrael.gov.il/currency.xml&quot;</defaultValue>
    <label>Current Exchange Rate Source URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Minutes_for_Daily_Update_Retry__c.field-meta.xml
<CustomField>
    <fullName>Minutes_for_Daily_Update_Retry__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Minutes for Daily Update Retry</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Currency__c/fields/Number_of_Daily_Update_Retries__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Daily_Update_Retries__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Number of Daily Update Retries</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestExchangeRateUpdateScheduleImpl.cls
@isTest(seeAllData=false)
global with sharing class TestExchangeRateUpdateScheduleImpl extends ExchangeRateUpdateScheduleImpl {
	public TestExchangeRateUpdateScheduleImpl() {
		super();
	}

	public TestExchangeRateUpdateScheduleImpl(Integer retryNumber, Date exchangeRateDate) {
		super(retryNumber, exchangeRateDate);
	}

	@TestSetup
	static void makeData() {
		Currency__c currencyData = new Currency__c(
			Current_Exchange_Rate_Source_URL__c = 'http://www.bankisrael.gov.il/currency.xml',
			Minutes_for_Daily_Update_Retry__c = 30,
			Number_of_Daily_Update_Retries__c = 10,
			Currency_Manager__c = ''
		);
		Database.insert(currencyData);
	}

	global override void execute(SchedulableContext ctx) {
		TestExchangeRateUpdateScheduleImpl.executeTest(retryNumber, exchangeRateDate);
	}

	@future(callout=true)
	public static void executeTest(Integer retryNumber, Date exchangeRateDate) {
		start(retryNumber, exchangeRateDate);
	}

	public static void start(Integer retryNumber, Date exchangeRateDate) {
		TestUpdateExchangeRate eru = new TestUpdateExchangeRate(retryNumber, exchangeRateDate);
		eru.rawData = '<CURRENCIES><LAST_UPDATE>2012-0404</LAST_UPDATE><CURRENCY><NAME>Dollar</NAME><UNIT>1</UNIT><CURRENCYCODE>USD</CURRENCYCODE><COUNTRY>USA</COUNTRY><RATE>3.745</RATE><CHANGE>0.591</CHANGE></CURRENCY></CURRENCIES>';
		eru.UpdateExchangeRate();
	}

	private static testMethod void testExchangeRateUpdateScheduleImpl() {
		ExchangeRateUpdateScheduleImpl e = new ExchangeRateUpdateScheduleImpl(0, system.Today());
		e = new ExchangeRateUpdateScheduleImpl();
		ExchangeRateUpdateScheduleImpl.execute(0, system.Today());
	}
}