force-app/main/default/objects/Account/fields/Carrier_File_Code__c.field-meta.xml
<CustomField>
    <fullName>Carrier_File_Code__c</fullName>
    <label>Carrier File Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/General__c/General__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>General</label>
</CustomObject>

force-app/main/default/objects/General__c/fields/Personal_Category__c.field-meta.xml
<CustomField>
    <fullName>Personal_Category__c</fullName>
    <description>SHould be populated with csv of categories.
Policy transaction with product definitions that point to these categories can be used to create multiple policies in one button click.</description>
    <label>Personal Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/Policy_Transaction__c.object-meta.xml
<CustomObject>
    <label>Policy Transaction</label>
    <nameField>
        <label>Policy Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Transaction</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Transaction__c/fields/Agent_Discount_Written_In_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Agent_Discount_Written_In_Carrier__c</fullName>
    <label>Agent Discount Written In Carrier</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Agent_number_from_Insurance_comapny__c.field-meta.xml
<CustomField>
    <fullName>Agent_number_from_Insurance_comapny__c</fullName>
    <label>Agent number from Insurance comapny</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Broker_Number__c.field-meta.xml
<CustomField>
    <fullName>Broker_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Number</label>
    <referenceTo>Novidea_HPC__Broker_Number__c</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Carrier_File_Code__c.field-meta.xml
<CustomField>
    <fullName>Carrier_File_Code__c</fullName>
    <label>Carrier File Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Carrier_Product__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Product</label>
    <referenceTo>Novidea_HPC__Carrier_Product__c</referenceTo>
    <relationshipLabel>רשומות פרודוקציה</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/client_Number_From_Agent__c.field-meta.xml
<CustomField>
    <fullName>client_Number_From_Agent__c</fullName>
    <label>client Number From Agent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Comments_Agent_number__c.field-meta.xml
<CustomField>
    <fullName>Comments_Agent_number__c</fullName>
    <label>Comments Agent number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/comments_customer_account__c.field-meta.xml
<CustomField>
    <fullName>comments_customer_account__c</fullName>
    <label>comments customer account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/comments_for_Account__c.field-meta.xml
<CustomField>
    <fullName>comments_for_Account__c</fullName>
    <label>comments for Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Comments_Insurance_Company__c.field-meta.xml
<CustomField>
    <fullName>Comments_Insurance_Company__c</fullName>
    <label>Comments Insurance Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Comments_Policy__c.field-meta.xml
<CustomField>
    <fullName>Comments_Policy__c</fullName>
    <label>Comments Policy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Commission_Written_In_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Commission_Written_In_Carrier__c</fullName>
    <label>Commission Written In Carrier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Transaction (Customer Account)</relationshipLabel>
    <relationshipName>Policy_Transaction1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/customer_full_name__c.field-meta.xml
<CustomField>
    <fullName>customer_full_name__c</fullName>
    <label>customer full name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/endorsement_number__c.field-meta.xml
<CustomField>
    <fullName>endorsement_number__c</fullName>
    <label>endorsement number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/file_name__c.field-meta.xml
<CustomField>
    <fullName>file_name__c</fullName>
    <label>file name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Identification_Type__c.field-meta.xml
<CustomField>
    <fullName>Identification_Type__c</fullName>
    <label>Identification Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Policy Number</fullName>
            </value>
            <value>
                <fullName>Full Auto</fullName>
            </value>
            <value>
                <fullName>Partially Auto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Insurance_Type__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Type__c</fullName>
    <label>Insurance Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>first val</fullName>
            </value>
            <value>
                <fullName>second val</fullName>
            </value>
            <value>
                <fullName>third val</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Insured_number__c.field-meta.xml
<CustomField>
    <fullName>Insured_number__c</fullName>
    <description>מספר לקוח או מספר חברה</description>
    <label>Insured number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Insured_Type__c.field-meta.xml
<CustomField>
    <fullName>Insured_Type__c</fullName>
    <label>Insured Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/is_Account_Found__c.field-meta.xml
<CustomField>
    <fullName>is_Account_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Account Found</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Is_Broker_Found__c.field-meta.xml
<CustomField>
    <fullName>Is_Broker_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Broker Found</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Is_carrier_Found__c.field-meta.xml
<CustomField>
    <fullName>Is_carrier_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is carrier Found</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Is_Customer_Located_By_Head_To_Tail__c.field-meta.xml
<CustomField>
    <fullName>Is_Customer_Located_By_Head_To_Tail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Customer Located By Head To Tail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Is_Policy_found__c.field-meta.xml
<CustomField>
    <fullName>Is_Policy_found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Policy found</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Novidea_HPC__Policy__c</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Policy_Content__c.field-meta.xml
<CustomField>
    <fullName>Policy_Content__c</fullName>
    <label>Policy Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Policy_number_from_Insurance_company__c.field-meta.xml
<CustomField>
    <fullName>Policy_number_from_Insurance_company__c</fullName>
    <label>Policy Number from Insurance company</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/premium__c.field-meta.xml
<CustomField>
    <fullName>premium__c</fullName>
    <label>premium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Premium_Currency__c.field-meta.xml
<CustomField>
    <fullName>Premium_Currency__c</fullName>
    <label>Premium Currency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Premium_neto__c.field-meta.xml
<CustomField>
    <fullName>Premium_neto__c</fullName>
    <label>Premium neto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Product_Def__c.field-meta.xml
<CustomField>
    <fullName>Product_Def__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Def.</label>
    <referenceTo>Novidea_HPC__Product_Def__c</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/product_from_insurance_company__c.field-meta.xml
<CustomField>
    <fullName>product_from_insurance_company__c</fullName>
    <label>product from insurance company</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>compatible</fullName>
            </value>
            <value>
                <fullName>not compatible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Vehicle_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Manufacturer__c</fullName>
    <label>Vehicle Manufacturer</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/vehicle_number__c.field-meta.xml
<CustomField>
    <fullName>vehicle_number__c</fullName>
    <label>vehicle number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchCreatePoliciesFromTxs.cls
global with sharing class BatchCreatePoliciesFromTxs implements Database.Batchable<Policy_Transaction__c>, Database.stateful{
    public Policy_Transaction__c[] txsToProcess;
    public String[] txIds;
    public BatchCreatePoliciesFromTxs (String[] txIds){
        this.txIds = txIds;
    }

	public static list<string> categoriesId = General__c.getInstance().Personal_Category__c==null?null:General__c.getInstance().Personal_Category__c.split(',');//diana
 	
    public BatchCreatePoliciesFromTxs (){}
       
    global Iterable<Policy_Transaction__c> start(Database.BatchableContext BC){
       //raniz 12/5/13 TODO: perhaps there should have been a rematch process first in case user did some matching actions but did not rematch
       system.debug('\'' + string.join(txIds,'\',\'') +'\'');
       system.debug(categoriesId);
       return [SELECT Policy__c, client_Number_From_Agent__c, endorsement_number__c, Agent_Discount_Written_In_Carrier__c,
                     Premium_Currency__c, Identification_Type__c, Effective_Date__c, Expiration_Date__c,Product_Def__c,Product_Def__r.Novidea_HPC__Category__c,//diana 29/07/13
                     Commission_Written_In_Carrier__c, customer_full_name__c, premium__c, Premium_neto__c, comments_customer_account__c,
                     is_Account_Found__c, Is_Broker_Found__c, Is_Policy_found__c, Is_carrier_Found__c, Customer_Account__r.Name,
                     Broker_Number__r.Name, Broker_Number__r.Novidea_HPC__Agency__r.Name, Carrier__r.Name, vehicle_number__c, product_from_insurance_company__c, Policy__r.Novidea_HPC__Carrier__c,
                     file_name__c, comments_for_Account__c, Status__c, Production_Date__c, Policy_number_from_Insurance_company__c, 
                     OwnerId, Name, Insured_number__c, Insured_Type__c,Policy__r.Novidea_HPC__Client__c, Policy__r.Novidea_HPC__Client__r.Name, 
                     Insurance_Type__c, Carrier_File_Code__c, Customer_Account__c, Comments_Policy__c, Client__c, Customer_Account__r.Owner.ProfileId, 
                     Comments_Insurance_Company__c, Comments_Agent_number__c, Carrier__c, Broker_Number__c, Agent_number_from_Insurance_comapny__c, 
                     Address__c,Policy_Content__c, Product_Def__r.Name, Carrier_Product__c, Is_Customer_Located_By_Head_To_Tail__c,
                     Vehicle_Manufacturer__c, Vehicle_Model__c, Product_Def__r.Novidea_HPC__Category__r.Policies_Owner__c,                      
                     Product_Def__r.Novidea_HPC__Category__r.Default_Team_Member_Role__c, 
                     Customer_Account__r.OwnerId
                FROM Policy_Transaction__c
                WHERE Id IN : txIds
                AND Policy__c = null
                //rz change 28/7/13:
                //AND Vehicle_Number__c != null
                AND Is_Broker_Found__c = true
                AND Carrier__c != null
                AND Product_Def__c != null
                AND is_Account_Found__c = true 
                AND Endorsement_Number__c = '0'
                AND Status__c = 'not compatible'
                AND Product_Def__r.Novidea_HPC__Category__c IN: categoriesId //diana
                ORDER BY Vehicle_Number__c 
                //rz change 28/7/13:
                NULLS FIRST];
    }
    
    global void execute(Database.BatchableContext BC, list<Policy_Transaction__c> scope){
        executeLogic(scope, isLastBatch(BC.getJobId()));
    }

    global void finish(Database.BatchableContext BC){
        
    } 

    private void executeLogic(list<Policy_Transaction__c> scope, boolean isLastBatch){
        prepareScope(scope, isLastBatch);
        mergeTransactionCO.createPoliciesInDB(scope);
    }

	public void prepareScope(list<Policy_Transaction__c> scope, boolean isLastBatch){
        if(txsToProcess==null) txsToProcess = new Policy_Transaction__c[]{};
        txsToProcess.addAll(scope);
        scope.clear();
        scope.addAll(txsToProcess);
        //keeps last txs for next round and removes them from scope
        if(!isLastBatch) txsToProcess = getLastSameVehicleNumberTxs(scope);
	}

    /*
        extracts the last txs that belong to the same vehicle number in order to pass them to the next bacth
        for processing
    */
    public list<Policy_Transaction__c> getLastSameVehicleNumberTxs(list<Policy_Transaction__c> scope){
        list<Policy_Transaction__c> retlist = new list<Policy_Transaction__c>();
        Policy_Transaction__c pt;
        String vehicleNumber = scope[scope.size()-1].Vehicle_Number__c;
        for(Integer i=scope.size()-1;i>=0;--i){
            pt = scope[i];
            //rz change 28/7/13: vehicleNumber!=null && 
            if(vehicleNumber!=null && vehicleNumber.equalsIgnoreCase(pt.Vehicle_Number__c))
                retlist.add(scope.remove(i));
            else break;
        }
        return retlist;
    }
    
    public boolean isLastBatch(Id jobId){
        AsyncApexJob a = [SELECT JobItemsProcessed, TotalJobItems FROM AsyncApexJob WHERE Id=:jobId];
        return a.TotalJobItems-a.JobItemsProcessed == 1; 
    }
    
    
    public static list<Policy_Transaction__c> createTxs(list<Novidea_HPC__Product_Def__c> prodefs, Account carrier){
        list<Policy_Transaction__c> txs = new list<Policy_Transaction__c>();
        Account acc = new Account(name='חשבון לקוח');
        insert acc;
        Novidea_HPC__Broker_Number__c bn = new Novidea_HPC__Broker_Number__c(
                                                                            Novidea_HPC__Broker_Number_In_Carrier__c = '56561',
                                                                            Novidea_HPC__Carrier__c = carrier.Id
                                                                            );
        insert bn;
		
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123451234',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123451234',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[1].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123451234',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        
        
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        /*txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '1'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '2'
        ));*/
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[1].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        /*txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = null,
            Policy_Number_From_Insurance_Company__c = '555555555',
            Product_Def__c = prodefs[3].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));*/


        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[1].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));

        insert txs;
        return txs;
    }
    //diana 29/07/2013
    public static list<Policy_Transaction__c> createTxsWithDwelling(list<Novidea_HPC__Product_Def__c> prodefs, Account carrier){
        list<Policy_Transaction__c> txs = new list<Policy_Transaction__c>();
        Account acc = new Account(name='חשבון לקוח');
        insert acc;
        Novidea_HPC__Broker_Number__c bn = new Novidea_HPC__Broker_Number__c(
                                                                            Novidea_HPC__Broker_Number_In_Carrier__c = '56561',
                                                                            Novidea_HPC__Carrier__c = carrier.Id
                                                                            );
        insert bn;
        
		
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = null,
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = null,
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[1].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = null,
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
         txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        
         txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
         txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '1234546789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
         txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '1234546789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        
        insert txs;
        return txs;
    }
       
    
    
    public static list<Novidea_HPC__Product_Def__c> createProductDefs(){
        list<Novidea_HPC__Product_Def__c> prodefs = new list<Novidea_HPC__Product_Def__c>();
        
    	General__c general = [SELECT Personal_Category__c FROM General__c][0];
    	map<string, Novidea_HPC__Product_Category__c> cats = new map<string, Novidea_HPC__Product_Category__c>{
    														'car'=>new Novidea_HPC__Product_Category__c(name='car'),
    														'flat'=>new Novidea_HPC__Product_Category__c(name='flat'),
    														'stam'=>new Novidea_HPC__Product_Category__c(name='stam')
    														};
    	insert cats.Values();
    	general.Personal_Category__c='';
    	for(Novidea_HPC__Product_Category__c cat: cats.values()){
    		general.Personal_Category__c+=cat.Id +',';
    	}
    	general.Personal_Category__c = general.Personal_Category__c.substring(0,general.Personal_Category__c.length()-1);
    	update general;
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='מקיף',Novidea_HPC__Category__c = cats.get('car').Id)); //diana added categoty
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='חובה',Novidea_HPC__Category__c = cats.get('car').Id));
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='ריידר',Novidea_HPC__Category__c = cats.get('car').Id));
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='סתם לא קשור לרכב',Novidea_HPC__Category__c = cats.get('stam').Id));
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='דירה',Novidea_HPC__Category__c = cats.get('flat').Id));
        
        insert prodefs;
        return prodefs;
    }
    
    public static Account createCarrier(){
        Id RecordTypeId = [select Id from recordType where sobjecttype='account' and developername = 'carrier' and isActive = true][0].id;
        Account a  = new Account(RecordTypeId=RecordTypeId, name= 'carrier');
        insert a;
        return a;
    }
  
}