force-app/main/default/objects/InboundDocument__c/InboundDocument__c.object-meta.xml
<CustomObject>
    <label>Inbound Document - ישן</label>
    <nameField>
        <displayFormat>DOC-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Documents - ישן</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InboundDocument__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <label>Date Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DocumentSearchFacade.cls
global with sharing class DocumentSearchFacade {
	global class SearchResult {
		public list<InboundDocument__c> documents {get;set;}
		public Integer maximumSize {get;set;}
	}
    @RemoteAction    
    global static SearchResult doRemoteSearch(String params){
        system.debug(params);
        DocumentSearchParams oParams = (DocumentSearchParams)Json.deserialize(params,DocumentSearchParams.class);
        system.debug(oParams);
        if(oParams==null)oParams = new DocumentSearchParams();
        if(null==oParams.orderby){
            oParams.orderby  = new DocumentSearchParams.DocumentSearchOrderByParam[]{};
        }
        if(!oParams.isOrderByFieldSet('Date_Received__c'))
            oParams.orderby.add(new DocumentSearchParams.DocumentSearchOrderByParam('Date_Received__c','DESC'));
        SearchResult result = new SearchResult();
        result.documents = DocumentSearchController.doRemoteSearch(oParams);
        result.maximumSize = DocumentSearchController.MAX_RECORDS;
        if (!String.isEmpty(oParams.freeText))
        	result.maximumSize = DocumentSearchController.LIMIT_SOSL_QUERY_RECORDS;
        return result;//JSON.serialize(docs);
    }
    
    public DocumentSearchFacade(DocumentSearchController searchController) {}
    public static Integer maxRecords {
    	get {
    		return DocumentSearchController.MAX_RECORDS;
    	}
    	private set;
    }
}