force-app/main/default/objects/InboundDocument__c/InboundDocument__c.object-meta.xml
<CustomObject>
    <label>Inbound Document - ישן</label>
    <nameField>
        <displayFormat>DOC-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Documents - ישן</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InboundDocument__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inbound_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/Attachments__c.field-meta.xml
<CustomField>
    <fullName>Attachments__c</fullName>
    <label>Attachments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <label>Date Received</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Claims</fullName>
                <default>true</default>
                <label>Claims</label>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Risk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId10__c.field-meta.xml
<CustomField>
    <fullName>EntId10__c</fullName>
    <label>EntId10</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId11__c.field-meta.xml
<CustomField>
    <fullName>EntId11__c</fullName>
    <label>EntId11</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId12__c.field-meta.xml
<CustomField>
    <fullName>EntId12__c</fullName>
    <label>EntId12</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId13__c.field-meta.xml
<CustomField>
    <fullName>EntId13__c</fullName>
    <label>EntId13</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId14__c.field-meta.xml
<CustomField>
    <fullName>EntId14__c</fullName>
    <label>EntId14</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId15__c.field-meta.xml
<CustomField>
    <fullName>EntId15__c</fullName>
    <label>EntId15</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId16__c.field-meta.xml
<CustomField>
    <fullName>EntId16__c</fullName>
    <label>EntId16</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId17__c.field-meta.xml
<CustomField>
    <fullName>EntId17__c</fullName>
    <label>EntId17</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId18__c.field-meta.xml
<CustomField>
    <fullName>EntId18__c</fullName>
    <label>EntId18</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId19__c.field-meta.xml
<CustomField>
    <fullName>EntId19__c</fullName>
    <label>EntId19</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId20__c.field-meta.xml
<CustomField>
    <fullName>EntId20__c</fullName>
    <label>EntId20</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId2__c.field-meta.xml
<CustomField>
    <fullName>EntId2__c</fullName>
    <label>EntId2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId3__c.field-meta.xml
<CustomField>
    <fullName>EntId3__c</fullName>
    <label>EntId3</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId4__c.field-meta.xml
<CustomField>
    <fullName>EntId4__c</fullName>
    <label>EntId4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId5__c.field-meta.xml
<CustomField>
    <fullName>EntId5__c</fullName>
    <label>EntId5</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId6__c.field-meta.xml
<CustomField>
    <fullName>EntId6__c</fullName>
    <label>EntId6</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId7__c.field-meta.xml
<CustomField>
    <fullName>EntId7__c</fullName>
    <label>EntId7</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId8__c.field-meta.xml
<CustomField>
    <fullName>EntId8__c</fullName>
    <label>EntId8</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId9__c.field-meta.xml
<CustomField>
    <fullName>EntId9__c</fullName>
    <label>EntId9</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>אישור כיסוי</fullName>
            </value>
            <value>
                <fullName>אישור כיסוי ללקוח</fullName>
            </value>
            <value>
                <fullName>אישור מס</fullName>
            </value>
            <value>
                <fullName>אישור פקס</fullName>
            </value>
            <value>
                <fullName>אישור קיום ביטוחים</fullName>
            </value>
            <value>
                <fullName>ביטול פוליסה</fullName>
            </value>
            <value>
                <fullName>בקשה לאישור קיום ביטוח</fullName>
            </value>
            <value>
                <fullName>ד. תשלום DEBIT NOTE</fullName>
            </value>
            <value>
                <fullName>דף סיכום פגישה</fullName>
            </value>
            <value>
                <fullName>דרישת תשלום</fullName>
            </value>
            <value>
                <fullName>הארכת פוליסה</fullName>
            </value>
            <value>
                <fullName>הנפקה ( פרטית / ציבורית)</fullName>
            </value>
            <value>
                <fullName>הסבה</fullName>
            </value>
            <value>
                <fullName>הסכם סודיות - NDA</fullName>
            </value>
            <value>
                <fullName>הצהרת העדר תביעות NCD</fullName>
            </value>
            <value>
                <fullName>הצעה (לקוח חדש)</fullName>
            </value>
            <value>
                <fullName>הצעה לחידוש</fullName>
            </value>
            <value>
                <fullName>הצעה מן המבטח</fullName>
            </value>
            <value>
                <fullName>חומר חדש מהלקוח</fullName>
            </value>
            <value>
                <fullName>חומר לחידוש מהלקוח</fullName>
            </value>
            <value>
                <fullName>חריג חדלות פרעון</fullName>
            </value>
            <value>
                <fullName>טבלת בעלי מניות</fullName>
            </value>
            <value>
                <fullName>טופס הצעה</fullName>
            </value>
            <value>
                <fullName>כולם</fullName>
            </value>
            <value>
                <fullName>כפיפויות</fullName>
            </value>
            <value>
                <fullName>כתבה על החברה</fullName>
            </value>
            <value>
                <fullName>כתב כיסוי</fullName>
            </value>
            <value>
                <fullName>כתב מינוי סוכן</fullName>
            </value>
            <value>
                <fullName>לחברת ביטוח Submission</fullName>
            </value>
            <value>
                <fullName>מייל ללקוח לאחר פגישה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Novidea_Document_Management__c/Novidea_Document_Management__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Novidea Document Management</label>
</CustomObject>

force-app/main/default/objects/Novidea_Document_Management__c/fields/Single_SMS_Impl_Class__c.field-meta.xml
<CustomField>
    <fullName>Single_SMS_Impl_Class__c</fullName>
    <inlineHelpText>Class name that implements SingleSMSIterface</inlineHelpText>
    <label>Single SMS Impl Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SelectEmailTemplateCo.cls
global with sharing class SelectEmailTemplateCo {

        public static list<ObjectsEmailFieldsCollector.EmailRecipient> NameAndEmails {
                get{
                        return ObjectsEmailFieldsCollector.getEmailAddrs( ApexPages.currentPage().getParameters().get('entid'));
                        
                }set;}
    public String getTemplateWindow() {
        //todo: handle parameters
        PageReference selectionPage = new PageReference('/email/author/templateselector.jsp?fcf=' + ApexPages.currentPage().getParameters().get('filterIds') + '&entid=' + ApexPages.currentPage().getParameters().get('entid'));
        return selectionPage.getContent().toString();
    }
    
   public string resultFieldId  {get {return 'resultFieldId';}set;}
    
    global class EmailTemplateData{
        public String subject;
        public String body;
    }
    
    
    @RemoteAction
    global static boolean sendSingleSMS(String smsBody, list<String> phonesList, String senderName,  String entId){
    
        Novidea_Document_Management__c settings = Novidea_Document_Management__c.getInstance();
        
        if (settings == null){
            system.debug('Novidea_Document_Management__c - not found');
            return false;
        }
            
        if (settings.Single_SMS_Impl_Class__c == null || settings.Single_SMS_Impl_Class__c == ''){
            system.debug('Single_SMS_Impl_Class__c - not set');
            return false;
        }             

        Type t = Type.forName(settings.Single_SMS_Impl_Class__c);
        SingleSMSInterface smsSingleImple = (SingleSMSInterface)t.newInstance();

        boolean success = smsSingleImple.sendSMS(smsBody, phonesList, senderName);
        
        createEmailTask('SMS', smsBody, entId, null);
        
        return success;
    
    }
    
    @RemoteAction
    global static String createEmailTask(String subject, String body, String entId, String[] docsIds){
        
                try {
                Task task = new Task();
                task.Subject = Label.Send_Email;
                task.ActivityDate = date.today();
                task.Priority = 'Normal';
                task.Description = subject + '\n' + body;
                task.Status = 'Completed';
                
                if (entId.indexOf('003') == 0)
                  task.WhoId = entId;         
                else
                  task.WhatId = entId; 
                  
                database.insert(task);
                
                system.debug(docs);
                
               if (docsIds != null && docsIds.size() >0)
                    for (ID docId : docsIds){
                        docs = null; //Igall, hack fix for some bug
                        attachFileToTask(task.Id,docId);
                    }    

                return task.id;
                    
                } catch (Exception e){
                        System.debug('Cannot create task or attach to task:' + e.getMessage());
                }
                
                return null;
    }
    
    @RemoteAction
    global static EmailTemplateData getTemplateContent(string templateId, string entId ,string docId) {

       
        EmailTemplateData ed = new EmailTemplateData();
                EmailTemplate eTemplate = new EmailTemplate() ;
                /*Messaging.SingleEmailMessage emailOut = new Messaging.SingleEmailMessage();
                emailOut.setTemplateId(templateId);
                emailOut.setTargetObjectId(entId);*/
                if(templateId != ''){ 
                eTemplate = [select Id,Name from EmailTemplate where id =:templateId];
                        
                ed.subject = getContentSubject(templateId);
                
                ed.body = getContent(templateId);
                }else{
                        ed.subject = '';
                ed.body = ''; 
                }
                           
        return ed;    
   }
    @RemoteAction
    private static InboundDocument__c[] docs;
    @RemoteAction
    public static  InboundDocument__c[] getDocuments(id taskId ,id docId){
        if (docs == null){
                        String docQuery = 'select Id, Name, Attachments__c, Comments__c, Date_Received__c, Department__c,'  
                                                        +'EntId10__c, EntId11__c, EntId12__c, EntId13__c, EntId14__c, EntId15__c, EntId16__c, EntId17__c, EntId18__c, EntId19__c, EntId20__c, EntId2__c, EntId3__c, EntId4__c, EntId5__c, EntId6__c, EntId7__c, EntId8__c, EntId9__c,' 
                                                        +'Private__c, Subject__c, Type__c, account__c ' 
                                        +'from InboundDocument__c where id ='+ '\'' + docId + '\'' +'AND (';
        
                String tempStr = '';
                        String whereClause = '';                
                for(integer i=2; i<=20; ++i){
                    whereClause+= (tempStr + ' EntId' + i + '__c = null');
                    tempStr = ' OR ';
                }
                whereClause+= ') ';
                system.debug(docQuery + whereClause);
                docs = Database.query(docQuery + whereClause); 
        }
        
        return docs;
    }
   @RemoteAction
   public static void attachFileToTask(Id taskId,Id docId ){
                // Add the new document to filing criteria
                boolean refiled = false;
        for(integer i=2; i<=20; ++i){
                String ent = 'EntId' + i + '__c';
                String entValue = (String)getDocuments(taskId,docId)[0].get(ent); 
                if (String.isBlank(entValue)){
                        getDocuments(taskId,docId)[0].put(ent, taskId);
                        update getDocuments(taskId,docId)[0];
                        refiled = true;
                        break; 
                }
        }
        // If there was no free EntId to add the new filing criteria, then send an alert
        if (!refiled){
                ForceUtils.emailException('CreateXFromDocumentTaskController: Failed adding filing criteria to the document: '+getDocuments(taskId,docId)[0].Id + ', needed criteria: ' + taskId, null, getDocuments(taskId,docId)[0].Id);
                ForceUtils.sendPendingEmails();
        }
   }
    
   public static String getContent(ID templateId){
                PageReference pr = new PageReference('/_ui/core/email/author/EmailAuthor?template_id='+templateId);
                String c = pr.getContent().ToString();
                String startStr = 'id="p7"';
                String endStr = '</';
                integer s = c.indexOf(startStr);
                s = c.indexOf('>', s) + 1;
                integer e =  c.indexOf(endStr, s);
                return c.substring(s, e);
   }
    
   public static String getContentSubject(ID templateId){
                PageReference pr = new PageReference('/_ui/core/email/author/EmailAuthor?template_id='+templateId);
                String c = pr.getContent().ToString();
                // TODO: Move to custom label
                String startStr = 'id="p6"';
                String endStr = '"';
                integer s = c.indexOf(startStr);
                s = c.indexOf('value="', s) + 7;
                integer e =  c.indexOf(endStr, s);              
                return c.substring(s, e);
    }
}