force-app/main/default/objects/InboundDocument__c/InboundDocument__c.object-meta.xml
<CustomObject>
    <label>Inbound Document - ישן</label>
    <nameField>
        <displayFormat>DOC-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Documents - ישן</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/InboundDocument__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inbound_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId10__c.field-meta.xml
<CustomField>
    <fullName>EntId10__c</fullName>
    <label>EntId10</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId11__c.field-meta.xml
<CustomField>
    <fullName>EntId11__c</fullName>
    <label>EntId11</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId12__c.field-meta.xml
<CustomField>
    <fullName>EntId12__c</fullName>
    <label>EntId12</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId13__c.field-meta.xml
<CustomField>
    <fullName>EntId13__c</fullName>
    <label>EntId13</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId14__c.field-meta.xml
<CustomField>
    <fullName>EntId14__c</fullName>
    <label>EntId14</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId15__c.field-meta.xml
<CustomField>
    <fullName>EntId15__c</fullName>
    <label>EntId15</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId16__c.field-meta.xml
<CustomField>
    <fullName>EntId16__c</fullName>
    <label>EntId16</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId17__c.field-meta.xml
<CustomField>
    <fullName>EntId17__c</fullName>
    <label>EntId17</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId18__c.field-meta.xml
<CustomField>
    <fullName>EntId18__c</fullName>
    <label>EntId18</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId19__c.field-meta.xml
<CustomField>
    <fullName>EntId19__c</fullName>
    <label>EntId19</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId1__c.field-meta.xml
<CustomField>
    <fullName>EntId1__c</fullName>
    <label>EntId1</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId20__c.field-meta.xml
<CustomField>
    <fullName>EntId20__c</fullName>
    <label>EntId20</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId2__c.field-meta.xml
<CustomField>
    <fullName>EntId2__c</fullName>
    <label>EntId2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId3__c.field-meta.xml
<CustomField>
    <fullName>EntId3__c</fullName>
    <label>EntId3</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId4__c.field-meta.xml
<CustomField>
    <fullName>EntId4__c</fullName>
    <label>EntId4</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId5__c.field-meta.xml
<CustomField>
    <fullName>EntId5__c</fullName>
    <label>EntId5</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId6__c.field-meta.xml
<CustomField>
    <fullName>EntId6__c</fullName>
    <label>EntId6</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId7__c.field-meta.xml
<CustomField>
    <fullName>EntId7__c</fullName>
    <label>EntId7</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId8__c.field-meta.xml
<CustomField>
    <fullName>EntId8__c</fullName>
    <label>EntId8</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InboundDocument__c/fields/EntId9__c.field-meta.xml
<CustomField>
    <fullName>EntId9__c</fullName>
    <label>EntId9</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConnectDocumentsToAccount.cls
global with sharing class ConnectDocumentsToAccount implements Schedulable, Database.Batchable<sObject>{
	public class ConnectDocumentsToAccountException extends Exception {}
    private Integer numOfRecsInBatch = 200;
    global void execute(SchedulableContext ctx){
        Database.executeBatch(new ConnectDocumentsToAccount(), numOfRecsInBatch);
    }
   public ConnectDocumentsToAccount(){}
   public ConnectDocumentsToAccount(Integer numOfRecsInBatch){this.numOfRecsInBatch = numOfRecsInBatch;}
   global Database.QueryLocator start(Database.BatchableContext BC){
   	  	String query = 'Select account__c, EntId1__c,EntId2__c,EntId3__c,EntId4__c,EntId5__c,EntId6__c, ' + 
                                ' EntId7__c,EntId8__c,EntId9__c,EntId10__c,EntId11__c,EntId12__c, ' + 
                                ' EntId13__c,EntId14__c,EntId15__c,EntId16__c,EntId17__c,EntId18__c, ' + 
                                ' EntId19__c,EntId20__c ' + 
					' From InboundDocument__c  ' ;
      	return Database.getQueryLocator(query);
   }

	global void execute(Database.BatchableContext BC, list<sObject> scope){
		if(scope.isEmpty())return;
		Database.update(scope);
	}

   global void finish(Database.BatchableContext BC){
   }
   /*
   	 Datetime dt = Datetime.now().addMinutes(1); //change minutes here
        String min = dt.minute()+'';
        String hour = dt.hour()+'';
        String day = dt.day()+'';
        String month = dt.month()+'';
        String year = dt.year()+'';
        //Seconds Minutes Hours Day_of_month Month Day_of_week optional_year
        final String CRON_EXP = '0 ' + min + ' ' + hour + ' ' + day + ' ' + month + ' ? ' + year;
        system.debug(CRON_EXP);
        ConnectDocumentsToAccount do1 = new ConnectDocumentsToAccount(200);
        do1.OBJECT_NAME = '';
        system.schedule('Connect Documents to Accounts ' + '(' + CRON_EXP + ')', CRON_EXP, do1);
   */
}