force-app/main/default/objects/General__c/General__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>General</label>
</CustomObject>

force-app/main/default/objects/General__c/fields/Personal_Category__c.field-meta.xml
<CustomField>
    <fullName>Personal_Category__c</fullName>
    <description>SHould be populated with csv of categories.
Policy transaction with product definitions that point to these categories can be used to create multiple policies in one button click.</description>
    <label>Personal Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/General__c/fields/Process_Compatible_Tx_Without_Account__c.field-meta.xml
<CustomField>
    <fullName>Process_Compatible_Tx_Without_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to decide whether to process policy tx when the account onj the tx is not recognized bu the status i scomopatible and there is a matching policy</description>
    <label>Process Compatible Tx Without Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/Policy_Transaction__c.object-meta.xml
<CustomObject>
    <label>Policy Transaction</label>
    <nameField>
        <label>Policy Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Transaction</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Transaction__c/fields/Agent_Discount_Written_In_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Agent_Discount_Written_In_Carrier__c</fullName>
    <label>Agent Discount Written In Carrier</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Broker_Number__c.field-meta.xml
<CustomField>
    <fullName>Broker_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Number</label>
    <referenceTo>Novidea_HPC__Broker_Number__c</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Carrier_Product__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Product</label>
    <referenceTo>Novidea_HPC__Carrier_Product__c</referenceTo>
    <relationshipLabel>רשומות פרודוקציה</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/client_Number_From_Agent__c.field-meta.xml
<CustomField>
    <fullName>client_Number_From_Agent__c</fullName>
    <label>client Number From Agent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Commission_Written_In_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Commission_Written_In_Carrier__c</fullName>
    <label>Commission Written In Carrier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Credit_Fee__c.field-meta.xml
<CustomField>
    <fullName>Credit_Fee__c</fullName>
    <label>Credit Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Customer_Account__c.field-meta.xml
<CustomField>
    <fullName>Customer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policy Transaction (Customer Account)</relationshipLabel>
    <relationshipName>Policy_Transaction1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/customer_full_name__c.field-meta.xml
<CustomField>
    <fullName>customer_full_name__c</fullName>
    <label>customer full name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Endorsement_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Effective_Date__c</fullName>
    <label>Endorsement Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Endorsement_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Endorsement_Expiration_Date__c</fullName>
    <label>Endorsement_Expiration_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/endorsement_number__c.field-meta.xml
<CustomField>
    <fullName>endorsement_number__c</fullName>
    <label>endorsement number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Errors_while_updating_Sobject__c.field-meta.xml
<CustomField>
    <fullName>Errors_while_updating_Sobject__c</fullName>
    <label>Errors while updating Sobject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/file_name__c.field-meta.xml
<CustomField>
    <fullName>file_name__c</fullName>
    <label>file name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Identification_Type__c.field-meta.xml
<CustomField>
    <fullName>Identification_Type__c</fullName>
    <label>Identification Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Policy Number</fullName>
            </value>
            <value>
                <fullName>Full Auto</fullName>
            </value>
            <value>
                <fullName>Partially Auto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Insured_number__c.field-meta.xml
<CustomField>
    <fullName>Insured_number__c</fullName>
    <description>מספר לקוח או מספר חברה</description>
    <label>Insured number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Insured_Type__c.field-meta.xml
<CustomField>
    <fullName>Insured_Type__c</fullName>
    <label>Insured Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/is_Account_Found__c.field-meta.xml
<CustomField>
    <fullName>is_Account_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Account Found</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Is_Broker_Found__c.field-meta.xml
<CustomField>
    <fullName>Is_Broker_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Broker Found</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Is_carrier_Found__c.field-meta.xml
<CustomField>
    <fullName>Is_carrier_Found__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is carrier Found</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Other_Commissions__c.field-meta.xml
<CustomField>
    <fullName>Other_Commissions__c</fullName>
    <label>Other Commissions</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Novidea_HPC__Policy__c</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Policy_Content__c.field-meta.xml
<CustomField>
    <fullName>Policy_Content__c</fullName>
    <label>Policy Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Policy_number_from_Insurance_company__c.field-meta.xml
<CustomField>
    <fullName>Policy_number_from_Insurance_company__c</fullName>
    <label>Policy Number from Insurance company</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/premium__c.field-meta.xml
<CustomField>
    <fullName>premium__c</fullName>
    <label>premium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Premium_Currency__c.field-meta.xml
<CustomField>
    <fullName>Premium_Currency__c</fullName>
    <label>Premium Currency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Premium_neto__c.field-meta.xml
<CustomField>
    <fullName>Premium_neto__c</fullName>
    <label>Premium neto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Product_Def__c.field-meta.xml
<CustomField>
    <fullName>Product_Def__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Def.</label>
    <referenceTo>Novidea_HPC__Product_Def__c</referenceTo>
    <relationshipLabel>Policy Transaction</relationshipLabel>
    <relationshipName>Policy_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>compatible</fullName>
            </value>
            <value>
                <fullName>not compatible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Vehicle_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Manufacturer__c</fullName>
    <label>Vehicle Manufacturer</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy_Transaction__c/fields/vehicle_number__c.field-meta.xml
<CustomField>
    <fullName>vehicle_number__c</fullName>
    <label>vehicle number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchUpdatePoliciesFromTxs.cls
global with sharing class BatchUpdatePoliciesFromTxs implements Database.Batchable<Policy_Transaction__c>, Database.stateful{
    
    private set<String> txIds;
    private Datetime startDatetime;
    private string errorString='';
    private integer batchCounter=0;
    
    public BatchUpdatePoliciesFromTxs(set<String> txIds){
        this.txIds = txIds; 
        startDatetime = Datetime.now();
    }
    
    global Iterable<Policy_Transaction__c> start(Database.BatchableContext BC){
        return [SELECT Policy__c, Carrier__c, client_Number_From_Agent__c, Policy_number_from_Insurance_company__c, Broker_Number__c,
                     Other_Commissions__c, premium__c, Premium_neto__c, endorsement_number__c, Agent_Discount_Written_In_Carrier__c, Commission_Written_In_Carrier__c,
                     Premium_Currency__c, Identification_Type__c, customer_full_name__c, Product_Def__c, Product_Def__r.Novidea_HPC__Category__r.Policies_Owner__c,
                     Errors_while_updating_Sobject__c,Status__c,Client__c, Policy_Content__c, Insured_number__c, Insured_Type__c, Credit_Fee__c, Fee__c, 
                     Customer_Account__c,Customer_Account__r.OwnerId, Customer_Account__r.Owner.ProfileId, Carrier_Product__c, File_Name__c, Vehicle_Manufacturer__c,
                     Vehicle_Model__c, Production_Date__c, Endorsement_Expiration_Date__c,Endorsement_Effective_Date__c,Expiration_Date__c,Effective_Date__c, Birthdate__c
                FROM Policy_Transaction__c
                WHERE Id IN : txIds
                ORDER BY Carrier__c, Policy__c, endorsement_number__c];
    }
    
    global void execute(Database.BatchableContext BC, list<Policy_Transaction__c> scope){
        batchCounter++;
        try{
            executeLogic(scope);
        }
        catch(exception e){
            errorString += String.format('{0} {1} {2}: {3}\r\n',new string[]{'אצווה','' + batchCounter,'הסתיימה עם שגיאה ',e.getmessage()});
            system.debug(errorString + ' ' + batchcounter);
        }
    }

    global void finish(Database.BatchableContext BC){
        String subjectPart = String.format('{0}-{1}',new String[]{'עיבוד התפוקות שהופעל ב',startDatetime.format('d/M/yyyy HH:mm','Asia/Jerusalem')});
        String subject = String.format('{0} {1}',new String[]{'סיום',subjectPart});
        sendEmail(String.format('{0} {1}\r\n{2}\r\n\r\n{3}', new string[]{subjectPart,'הסתיים.','.נא להכנס למסך מיזוג התפוקות או לרענן מסך פתוח', errorString}), subject, new string[]{Userinfo.getUserEmail()});
    } 
    
    private class FailureException extends Exception{}
    
    public void executeLogic(list<Policy_Transaction__c> scope){
        map<Id, list<mergeTransactionCO.RowIdentifier>> jsonTxByCarrier = new map<Id, list<mergeTransactionCO.RowIdentifier>>();
        list<mergeTransactionCO.RowIdentifier> tmpJsonList;
        integer counter = 0;
        for(Policy_Transaction__c pt: scope){
            if((tmpJsonList= jsonTxByCarrier.get(pt.carrier__c))==null){
                tmpJsonList = new list<mergeTransactionCO.RowIdentifier>();
            }
            tmpJsonList.add(new mergeTransactionCO.RowIdentifier(pt.Id,++counter+''));
            jsonTxByCarrier.put(pt.carrier__c, tmpJsonList);
        }
        for(Id key: jsonTxByCarrier.keyset()){
            mergeTransactionCO.updateRowTransactions(JSON.serialize(jsonTxByCarrier.get(key)),General__c.getInstance().Process_Compatible_Tx_Without_Account__c==true);
            //throw new FailureException('Exception in ' +  batchCounter + ' Batch');
        }
    }
    
    private void sendEmail(String msg, String subject, string[] emails){
        Messaging.reserveSingleEmailCapacity(1);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setCharset('UTF-8');
        mail.setToAddresses(emails);
        mail.setSubject(subject);
        String singleObjDetails = '';
        mail.setPlainTextBody(msg);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
	public static list<Policy_Transaction__c> createTxs(list<Novidea_HPC__Product_Def__c> prodefs, Account carrier){
        list<Policy_Transaction__c> txs = new list<Policy_Transaction__c>();
        Account acc = new Account(name='חשבון לקוח');
        insert acc;
        Novidea_HPC__Broker_Number__c bn = new Novidea_HPC__Broker_Number__c(
                                                                            Novidea_HPC__Broker_Number_In_Carrier__c = '56561',
                                                                            Novidea_HPC__Carrier__c = carrier.Id
                                                                            );
        insert bn;
		
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123451234',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123451234',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[1].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123451234',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        
        
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        /*txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '1'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '2'
        ));*/
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[1].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123456789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        /*txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = null,
            Policy_Number_From_Insurance_Company__c = '555555555',
            Product_Def__c = prodefs[3].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));*/


        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[0].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[1].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));
        
        txs.add(new Policy_Transaction__c(
            Vehicle_Number__c = '123956789',
            Policy_Number_From_Insurance_Company__c = '987654321',
            Product_Def__c = prodefs[2].id,
            Carrier__c = carrier.Id,
            Customer_Account__c =  acc.id,
            Broker_Number__c = bn.Id,
            Is_Broker_Found__c = true,
            Is_carrier_Found__c = true,
            is_Account_Found__c = true,
            Endorsement_Number__c = '0'
        ));

        insert txs;
        return txs;
    }

    public static list<Novidea_HPC__Product_Def__c> createProductDefs(){
        list<Novidea_HPC__Product_Def__c> prodefs = new list<Novidea_HPC__Product_Def__c>();
        
    	General__c general = [SELECT Personal_Category__c FROM General__c][0];
    	map<string, Novidea_HPC__Product_Category__c> cats = new map<string, Novidea_HPC__Product_Category__c>{
    														'car'=>new Novidea_HPC__Product_Category__c(name='car'),
    														'flat'=>new Novidea_HPC__Product_Category__c(name='flat'),
    														'stam'=>new Novidea_HPC__Product_Category__c(name='stam')
    														};
    	insert cats.Values();
    	general.Personal_Category__c='';
    	for(Novidea_HPC__Product_Category__c cat: cats.values()){
    		general.Personal_Category__c+=cat.Id +',';
    	}
    	general.Personal_Category__c = general.Personal_Category__c.substring(0,general.Personal_Category__c.length()-1);
    	update general;
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='מקיף',Novidea_HPC__Category__c = cats.get('car').Id)); //diana added categoty
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='חובה',Novidea_HPC__Category__c = cats.get('car').Id));
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='ריידר',Novidea_HPC__Category__c = cats.get('car').Id));
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='סתם לא קשור לרכב',Novidea_HPC__Category__c = cats.get('stam').Id));
        prodefs.add(new Novidea_HPC__Product_Def__c(Name='דירה',Novidea_HPC__Category__c = cats.get('flat').Id));
        
        insert prodefs;
        return prodefs;
    }
    
    public static Account createCarrier(){
        Id RecordTypeId = [select Id from recordType where sobjecttype='account' and developername = 'carrier' and 	IsActive = true][0].id;
        Account a  = new Account(RecordTypeId=RecordTypeId, name= 'carrier');
        insert a;
        return a;
    }
}