force-app/main/default/objects/Commission_Staging__c/Commission_Staging__c.object-meta.xml
<CustomObject>
    <description>A staging object for loading commissions from CSVs and creating Novidea Commissions records</description>
    <label>טעינת עמלה</label>
    <nameField>
        <displayFormat>Cs-{00000000}</displayFormat>
        <label>עמלה #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>טעינת עמלות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Upload_Field_Mapping__mdt/Commission_Upload_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Commission Upload Field Mapping</label>
    <pluralLabel>Commission Upload Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Commission_Upload_Field_Mapping__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <inlineHelpText>The API name of the field in Commission_Staging__c object</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission_Upload_Field_Mapping__mdt/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <inlineHelpText>the Commission_Upload__c RT name</inlineHelpText>
    <label>Format</label>
    <referenceTo>Commission_Upload_Format__mdt</referenceTo>
    <relationshipLabel>Commission Upload Field Mappings</relationshipLabel>
    <relationshipName>Commission_Upload_Field_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Commission_Upload_Field_Mapping__mdt/fields/Input_Type__c.field-meta.xml
<CustomField>
    <fullName>Input_Type__c</fullName>
    <label>Input Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
                <default>true</default>
                <label>text</label>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Commission_Upload_Field_Mapping__mdt/fields/Is_Input_Value__c.field-meta.xml
<CustomField>
    <fullName>Is_Input_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Input Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Commission_Upload_Format__mdt/Commission_Upload_Format__mdt.object-meta.xml
<CustomObject>
    <label>Commission Upload Format</label>
    <pluralLabel>Commission Upload Formats</pluralLabel>
</CustomObject>

force-app/main/default/objects/Commission_Upload_Format__mdt/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LWC_CommissionsUpload.cls
public with sharing class LWC_CommissionsUpload {
    @AuraEnabled(cacheable=true)
    public static List<Commission_Upload_Format__mdt> getFormatsMD(){
        try {
            return [SELECT MasterLabel, DeveloperName, Record_Type__c,
                    (SELECT MasterLabel, Field_API_Name__c, Default_Value__c, Is_Input_Value__c, Input_Type__c FROM Commission_Upload_Field_Mappings__r) 
                    FROM Commission_Upload_Format__mdt 
                    ORDER BY MasterLabel];
        } catch (Exception e) { throw new AuraHandledException(e.getMessage()); }
    }

    @AuraEnabled
    public static void saveRecords(List<Commission_Staging__c> records){
        try {
            insert records;
            // List<Commission_Staging__c> tempList = new List<Commission_Staging__c>();
            // for (Commission_Staging__c commission : records) {
            //     tempList.add(commission);

            //     if(tempList.size() == 10){
            //         insert tempList;
            //         tempList = new List<Commission_Staging__c>();
            //     }
            // }
            // insert tempList;
        } catch (Exception e) {throw new AuraHandledException(e.getMessage());}
    }
}