force-app/main/default/objects/Commission_Staging__c/Commission_Staging__c.object-meta.xml
<CustomObject>
    <description>A staging object for loading commissions from CSVs and creating Novidea Commissions records</description>
    <label>טעינת עמלה</label>
    <nameField>
        <displayFormat>Cs-{00000000}</displayFormat>
        <label>עמלה #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>טעינת עמלות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission_Staging__c/fields/Commission_Amount__c.field-meta.xml
<CustomField>
    <fullName>Commission_Amount__c</fullName>
    <label>טעינה - סכום עמלה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Commission_Staging__c/fields/Currency_Name__c.field-meta.xml
<CustomField>
    <fullName>Currency_Name__c</fullName>
    <label>טעינה - מטבע</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission_Staging__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>טעינה - שם מבוטח</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Commission_Staging__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <label>טעינה - מספר פוליסה</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LWC_CommissionsUpload_TEST.cls
@isTest
public with sharing class LWC_CommissionsUpload_TEST {
    @IsTest
    static void testFileSave(){        
        Test.startTest();
        LWC_CommissionsUpload.getFormatsMD();
        List<Commission_Staging__c> records = new List<Commission_Staging__c>();
        for (Integer i = 0; i < 60; i++) {
            records.add(new Commission_Staging__c(Policy_Number__c = '400000' + i,           
                                                    Customer_Name__c = 'Test',
                                                    Currency_Name__c = '1',
                                                    Commission_Amount__c = 100));
        }
        LWC_CommissionsUpload.saveRecords(records);

        Test.stopTest();        
    }
}